;;; Object identity and extraction diagnostics, without enumerating the catalog.
(use-modules (guix packages) (guix build-system gnu) (json) (srfi srfi-64) (rnrs bytevectors))
(load (string-append (dirname (current-filename)) "/../data/guix-index-core.scm"))
(test-runner-factory (lambda () (let ((r (test-runner-simple)))
                                (test-runner-on-test-end! r test-on-test-end-simple)
                                r)))
(define leaf
  (package (name "same") (version "1") (source #f)
           (build-system gnu-build-system) (synopsis "") (description "")
           (home-page "") (license #f)))
(define variant (package (inherit leaf)))
(define root
  (package (inherit leaf) (name "root")
           (inputs (list leaf variant)) (native-inputs (list leaf))))
(define (document p)
  (json-string->scm
   (call-with-output-string
    (lambda (out) (write-index (collect-package-graph (list p) (lambda _ #t))
                               "fixture" "0" out (current-error-port))))))
(define (field o k) (assoc-ref o k))
(test-begin "guix-indexer")
(test-assert "distinct objects" (not (eq? leaf variant)))
(let* ((doc (document root)) (ps (field doc "packages")) (p (vector-ref ps 0)))
  (test-equal "schema" 4 (field (field doc "header") "schema"))
  (test-equal "private closure" 3 (vector-length ps))
  (test-equal "distinct input IDs" '#(1 2) (field p "inputs"))
  (test-equal "same object across kinds" '#(1) (field p "native_inputs"))
  (test-equal "catalog root" #t (field p "catalog"))
  (test-equal "private variant" #f (field (vector-ref ps 2) "catalog"))
  (test-equal "complete" '#() (field doc "diagnostics")))
(let* ((p (package (inherit root) (inputs `(("leaf" ,leaf "out")))))
       (doc (document p)))
  (test-equal "label/output tuple" '#(1)
              (field (vector-ref (field doc "packages") 0) "inputs")))
(let* ((p (package (inherit root) (inputs (error "deliberate accessor failure"))))
       (doc (document p)))
  (test-equal "accessor failure is visible" "accessor-failed"
              (field (vector-ref (field doc "diagnostics") 0) "code")))
(let* ((p (package (inherit leaf) (inputs (list 12345)))) (doc (document p)))
  (test-equal "unknown input is visible" "unsupported-input"
              (field (vector-ref (field doc "diagnostics") 0) "code")))
(let* ((cycle (list "label"))
       (_ (set-cdr! cycle cycle))
       (p (package (inherit leaf) (inputs (list cycle)))))
  (test-equal "cyclic input is bounded" "unsupported-input"
              (field (vector-ref (field (document p) "diagnostics") 0) "code")))
(let* ((source (origin (method (lambda _ #f)) (uri "file:///not-fetched")
                       (sha256 (make-bytevector 32 0))))
       (p (package (inherit leaf) (inputs (list source)))))
  (test-equal "origins do not become packages" 1
              (vector-length (field (document p) "packages"))))
(let ((failed (test-runner-fail-count (test-runner-current))))
  (test-end "guix-indexer")
  (exit (if (zero? failed) 0 1)))
